Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.Helper;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection.Metadata;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork=unitOfWork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string SearchValue = "")
        {
            IEnumerable<Employee> employees;
            IEnumerable<EmployeeViewModel> mappedEmployees;

            if (string.IsNullOrEmpty(SearchValue))
                employees = await _unitOfWork.employeeRepository.GetAllAsync();
            
            else
                employees = _unitOfWork.employeeRepository.Search(SearchValue);
           
            mappedEmployees = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
            await _unitOfWork.CompleteAsync();

            return View(mappedEmployees);
        }


        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await _unitOfWork.departmentRepository.GetAllAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            ModelState["Department"].ValidationState = ModelValidationState.Valid;
            if (ModelState.IsValid)
            {
                #region Manual Mapping
                #endregion
                employeeVM.ImageUrl = DocumentSettings.UploadFile(employeeVM.Image, "Images");
                var mappedEmployee = _mapper.Map<Employee>(employeeVM);

                await _unitOfWork.employeeRepository.AddAsync(mappedEmployee);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = await _unitOfWork.departmentRepository.GetAllAsync();
            return View(employeeVM);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
                return NotFound();

            var employee = await _unitOfWork.employeeRepository.GetByIdAsync(id);
            var mappedEmployees = _mapper.Map<EmployeeViewModel>(employee);

            if(mappedEmployees == null)
                return NotFound();

            ViewBag.Departments = await _unitOfWork.employeeRepository.GetAllAsync();
            return View(mappedEmployees);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if(id  == null)
                return NotFound();

            var employee = await _unitOfWork.employeeRepository.GetByIdAsync(id);
            var mappedEmployees = _mapper.Map<EmployeeViewModel>(employee);

            if(mappedEmployees == null)
                return NotFound();

            ViewBag.Departments = await _unitOfWork.departmentRepository.GetAllAsync();
            return View(mappedEmployees);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, EmployeeViewModel employeeVM)
        {
            if(id != employeeVM.Id)
                return NotFound();

            try
            {
                ModelState["Department"].ValidationState = ModelValidationState.Valid;
                if (ModelState.IsValid)
                {
                    var mappedEmployee = _mapper.Map<Employee>(employeeVM);
                    
                    if(employeeVM.ImageUrl is not  null)
                        mappedEmployee.ImageUrl = DocumentSettings.UploadFile(employeeVM.Image, "Images");

                    _unitOfWork.employeeRepository.Update(mappedEmployee);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction(nameof(Index));
                }

            } catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
            ViewBag.Departments = await _unitOfWork.departmentRepository.GetAllAsync();
            return View(employeeVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await _unitOfWork.employeeRepository.GetByIdAsync(id);
            var mappedEmployees = _mapper.Map<EmployeeViewModel>(employee);

            if (mappedEmployees == null)
                return NotFound();

            ViewBag.Departments = await _unitOfWork.departmentRepository.GetAllAsync();
            return View(mappedEmployees);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id, Employee employee)
        {
            if(id != employee.Id)
                return NotFound();

            try
            {
                
                _unitOfWork.employeeRepository.Delete(employee);
                var Result = await _unitOfWork.CompleteAsync();
                if (Result > 0 && employee.ImageUrl is not null)
                    DocumentSettings.DeleteFile(employee.ImageUrl, "Images");

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employee);
            }
            
        }
    }
}

Demo.PL/Controllers/RolesController.cs
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly ILogger<RolesController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;

        public RolesController(RoleManager<ApplicationRole> roleManager,
                               ILogger<RolesController> logger,
                               UserManager<ApplicationUser> userManager) 
        {
            _roleManager = roleManager;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();

            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ApplicationRole role)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(role);

                if(result.Succeeded)
                    return RedirectToAction(nameof(Index));

                foreach(var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(role);
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id == null)
                return NotFound();

            var roles = await _roleManager.FindByIdAsync(id);

            if (roles == null)
                return NotFound();
            
            return View(viewName, roles);
        }

        public async Task<IActionResult> Update(string id)
        {
            return await Details(id, "Update");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, ApplicationRole applicationRole)
        {
            if(id != applicationRole.Id)
                return NotFound();

            if(ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);

                    role.Name = applicationRole.Name;
                    role.NormalizedName = applicationRole.Name.ToUpper();

                    var result = await _roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                        return RedirectToAction(nameof(Index));

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                }
            }

            return View(applicationRole);
        }
        public async Task<IActionResult> Delete(string id, ApplicationRole applicationRole)
        {
            if(id != applicationRole.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);

                    var result = await _roleManager.DeleteAsync(role);

                    if(result.Succeeded)
                        return RedirectToAction(nameof(Index));

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"{ex.Message}");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(applicationRole);
        }

        public async Task<IActionResult> AddOrRemoveUsers (string roleId)
        {
            var role = await _roleManager.FindByIdAsync (roleId);

            if(role == null)
                return NotFound();

            ViewBag.RoleId = roleId;

            var users = new List<UserInRoleViewModel>();

            foreach(var user in await _userManager.Users.ToListAsync())
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserName = user.UserName,
                    UserId = user.Id,
                };
                if(await _userManager.IsInRoleAsync(user, role.Name))
                    userInRole.IsSelected = true;
                else
                    userInRole.IsSelected = false;

                users.Add(userInRole);
            }

            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleViewModel> users, string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
                return NotFound();

            if(ModelState.IsValid)
            {
                foreach(var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);

                    if (appUser != null)
                    {
                        if (user.IsSelected && !(await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.AddToRoleAsync(appUser, role.Name);

                        else if (!user.IsSelected && (await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);

                    }
                }

                return RedirectToAction(nameof(Update), new {id = roleId});
            }

            return View(users);
        }
    }
}

Demo.PL/Controllers/UsersController.cs
using Demo.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Demo.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger _logger;

        public UsersController(UserManager<ApplicationUser> userManager, ILogger<UsersController> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }
        public async Task<IActionResult> Index(string SearchValue= "")
        {
            List<ApplicationUser> users;
            if (string.IsNullOrEmpty(SearchValue))
                users = await _userManager.Users.ToListAsync();
            else
                users = await _userManager.Users.Where(user => user.UserName.Trim().ToLower().Contains(SearchValue.Trim().ToLower())).ToListAsync();

            return View(users);
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null)
                return NotFound();

            var user = await _userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();

            return View(viewName, user);
        }

        public async Task<IActionResult> Update(string id)
        {
            return await Details(id, "Update");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, ApplicationUser applicationUser)
        {
            if(id != applicationUser.Id)
                return NotFound();
            if(ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);

                    user.UserName = applicationUser.UserName;
                    user.NormalizedUserName = applicationUser.UserName.ToUpper();

                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                        return RedirectToAction(nameof(Index));

                    foreach(var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                }
            }
            return View(applicationUser);
        }

        public async Task<IActionResult> Delete(string id, ApplicationUser applicationUser)
        {
            if(id != applicationUser.Id)
                return NotFound();

            try
            {
                var user = await _userManager.FindByIdAsync(id);

                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                    return RedirectToAction(nameof(Index));
                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title> @ViewData["Title"] </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"]</h1>
		@RenderBody()
		
		<div class="colorlibcopy-agile">
			<p>© @DateTime.Now.Year Colorlib Signup Form. All rights reserved></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("Scripts", required: true)
</body>
</html>

Demo.PL/Views/Shared/_ButtonPartialView.cshtml
@model int
<td>
    <a asp-action="Details" asp-route-id="@Model"> <i class="fas fa-eye" style="color: green;"></i> </a>
</td>
<td>
    <a asp-action="Update" asp-route-id="@Model"> <i class="fas fa-edit"></i> </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model"> <i class="fas fa-trash" style="color: red;"></i></a>
</td>

Demo.PL/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }
                    </ul>

                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-light btn btn-danger " asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>